### PR TITLE
Fix over-/underlinkings

### PR DESCRIPTION
**Pull request by rohieb**
Via [Sebastian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809923#24): libnordlicht is underlinked, nordlicht is overlinked. CMake seems to do strange things regarding the transitivity of linked libraries. Found no obvious way to fix this.

### CODE REVIEW

**Comment by rohieb** [comment]
Okay, I did a bit of reading.

Background and problem statement is nicely illustrated on the [Debian mailing list][1] and [the Mandriva wiki archive][2], fix is in this PR.

I got rid of overlinking in `nordlicht` by passing `-Wl,--as-needed` to the linker. We don't need any FFMPEG symbols in the exe itself, only in the lib, which pulls them in at runtime through the dynamic loader. Basically every Linux distribution these days uses dynamic loading, but in case someone wants to build a static executable, I only included the option when we're really building dynamically :) Although this might not be the best way of doing this in CMake, it Works For Me™.

I also updated the pkg-config file and moved the FFMPEG dependencies to the `Requires.private` and `Libs.private` fields, as stated by Steve Langasek on the [Debian list][1]. Those fields were introduced in pkg-config v0.18, which was released in 2005, so it should be available on all relevant systems by now.

[1]: https://lists.debian.org/debian-devel-announce/2005/11/msg00016.html
[2]: http://archive.openmandriva.org/wiki/en/index.php?title=Overlinking

This is all new to me, I have only a slight idea of what I'm doing, so although this works for me, feel free to correct things :-)

Oh, and Travis keeps failing because of things in `cheat.h`, so at least that one is totally not my fault :palm_tree:

**Comment by rohieb** [comment]
@cinemast, with these patches applied to the Debian collab-maint git tree from
your ITP bug, lintian does not complain anymore about useless library
dependencies (at least on my system).

**Comment by cinemast** [comment]
@rohieb, thank you. I will check on that.

**Comment by blinry** [comment]
@rohieb, wow, thanks for your work on that! Sorry for the failing tests, I'll look at what went wrong there.

As for the overlinking issue, I can confirm that this solves the issue on my machine :) Your changes to the pkg-config file also look very reasonable!

**Comment by blinry** [comment]
I fixed the test suite in 27c697c7dd35.

**Comment by rohieb** [comment]
On 22.01.2016 11:30, Sebastian Morr wrote:
> As for the overlinking issue, I can confirm that this solves the issue on my
> machine :) Your changes to the pkg-config file also look very reasonable!

Gooood :) TBH, this was bugging me since the first deb package, but my Google Fu
was not strong enough back then :)

**Comment by cinemast** [comment]
I can also verify it works. I will try to prepare a patch for Multi-Arch support. After that I will try to get a second review from Sebastian. 

Thank you very much @rohieb!

**Pull request merged**
